[package]
name = "tsorak"
version = "0.1.0"
authors = ["troido <troido@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pancurses = "0.16.1"
cgmath = "0.18"
